
project_id = "tzawsihjrndgmaartefg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[realtime]
enabled = true
webhooks_enabled = false

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = 52428800

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
email_template_fetch_redirect_url = "https://svqwqdnnxqcvpeirgscb.supabase.co/functions/v1/embed-email-template"

[auth.email]
enable_confirmations = false
double_confirm_changes = true
enable_sign_up = true

[functions]
enabled = true
ports = []

[functions.create-payment-intent]
verify_jwt = true
