
project_id = "tzawsihjrndgmaartefg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[storage]
enabled = true
port = 5000

[auth]
enabled = true
port = 9999

[inbucket]
enabled = true
port = 54324

[vector]
enabled = true
port = 54323

[studio]
enabled = true
port = 6370

[functions]
[functions.create-payment-intent]
verify_jwt = true

[functions.send-booking-notification]
verify_jwt = true

[functions.log-user-activity]
verify_jwt = true
