// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzawsihjrndgmaartefg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6YXdzaWhqcm5kZ21hYXJ0ZWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4Njc2NDYsImV4cCI6MjA1OTQ0MzY0Nn0.zLo_YNOQka-PB-ndxi0Nvv960Z4j7mtp9qMdpgKJ_fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);